# Generated by Django 3.2.12 on 2022-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220324_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
