# Generated by Django 3.2.13 on 2022-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidates_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
            ],
        ),
    ]
